[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "machine_readable_xlsx"
version = "0.1.0"
description = "Guidelines and Python tools for structuring Excel workbooks to reliably extract their data."
authors = [{ name = "EECA", email = "DataAndAnalytics@eeca.govt.nz" }]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
